apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: chalupa-bot
  namespace: chalupa-bot-prod
spec:
  interval: 1m
  url: https://github.com/olivercodes/chalupa-bot
  ref:
    branch: main
