apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: chalupa-bot-prod
  namespace: chalupa-bot-prod
spec:
  imageRepositoryRef:
    name: chalupa-bot
  filterTags:
   pattern: '.*-rc.*'
  policy:
    semver:
      range: '^1.x-0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: chalupa-bot
  namespace: chalupa-bot-prod
spec:
  image: ghcr.io/olivercodes/chalupa-bot
  interval: 30s
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: chalupa-bot
  namespace: chalupa-bot-prod
spec:
  interval: 1m
  url: https://github.com/olivercodes/chalupa-bot
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: chalupa-bot
  namespace: chalupa-bot-prod
spec:
  interval: 1m
  path: "./manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: chalupa-bot
    namespace: chalupa-bot-prod
